# Generated by Django 4.0.2 on 2022-02-16 16:37

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockimage',
            name='lock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.lock'),
        ),
        migrations.AlterField(
            model_name='nearyby',
            name='lock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='nearbies', to='api.lock'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='videoNearby',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='phase',
            name='videoView',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='phaseimage',
            name='phase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.phase'),
        ),
    ]
