# Generated by Django 4.0.2 on 2022-02-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lock_videonearby_alter_lock_videoview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='videoNearby',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lock',
            name='videoView',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phase',
            name='videoNearby',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phase',
            name='videoView',
            field=models.CharField(max_length=100),
        ),
    ]
