# Generated by Django 4.0.2 on 2022-02-16 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_lock_videonearby_alter_lock_videoview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lock',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='slug',
        ),
        migrations.AlterField(
            model_name='lock',
            name='phase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='phase_lock', to='api.phase'),
        ),
    ]
