# Generated by Django 4.0.2 on 2022-02-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_lock_slug_remove_phase_slug_alter_lock_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='videoHealth',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
